// Code generated by hero.
// source: /Users/huxin/DockerVolumes/Nginx/www/over-blog/back-end/Go/iris/views/layout.html
// DO NOT EDIT!
package template

import (
	"blog/models"
)

var (
	Config        = make(map[string]string)
	Category      = make([]*models.Category, 0)
	SocialData    = make([]models.Config, 0)
	RecentComment = make([]models.RecentComment, 0)
	FooterData    = make(map[string]map[int64]models.SimpleConfig)
	Link          = make([]models.SimpleLink, 0)
	Tag           = make([]models.Tag, 0)
	HotArticle    = make([]map[string]string, 0)
	AuthInfo      = make(map[string]string)
	CsrfToken     = ""
	AppUrl        = ""
)
