<?php
/**
 * Created by huxin.
 * User: huxin
 * Date: 2019-02-22
 * Time: 11:26
 */

namespace backend\controllers;


use app\models\Category;

class CategoryController extends BasicController
{
    public $enableCsrfValidation = false;
    private $category;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->category = new Category();
    }

    /**
     * 获取分类列表
     * Date: 2019-02-25 11:07
     * @return \yii\web\Response
     */
    public function actionCategoryList()
    {
        $list = $this->category->find()
            ->with('children')
            ->where(['pid'=>0])
            ->asArray()
            ->all();
        if(!empty($list)){
            foreach ($list as &$item)
            {
                $item['expand'] = true;
            }
            unset($item);
            return $this->success('获取分类列表成功！',$list);
        }
        return $this->error('获取分类列表失败，请稍后再试！');
    }

    /**
     * 添加分类
     * Date: 2019-02-25 11:21
     * @return \yii\web\Response
     */
    public function actionCategoryAdd()
    {
        $data = $this->post();
        $this->category->scenario = 'categoryAdd';
        $this->category->attributes = $data;
        if($this->category->validate()){
            $res = $this->category->save(false);
            return $res?$this->success('添加分类成功！')
                :$this->error('添加分类失败，请稍后再试！');
        }
        return $this->error(current($this->category->firstErrors));
    }

    /**
     * 修改分类信息
     * Date: 2019-02-25 11:23
     * @return \yii\web\Response
     */
    public function actionCategoryUpdate()
    {
        $data = $this->post();
        $this->category->scenario = 'categoryUpdate';
        $this->category->attributes = $data;
        if($this->category->validate()){
            $exist_category = $this->category->findOne($data['id']);
            $res = $exist_category->save(false,['title','pid','updated_at']);
            return $res?$this->success('添加分类成功！')
                :$this->error('添加分类失败，请稍后再试！');
        }
        return $this->error(current($this->category->firstErrors));
    }

    /**
     * 删除分类
     * Date: 2019-02-25 11:25
     * @return \yii\web\Response
     */
    public function actionDelCategory()
    {
        $data = $this->post();
        $this->category->scenario = 'delCategory';
        $this->category->attributes = $data;
        if($this->category->validate()){
            $exist_tag = $this->category->findOne($data['id']);
            $res = $exist_tag->delete();
            return $res?$this->success('删除分类成功！')
                :$this->error('删除分类失败，请稍后再试！');
        }
        return $this->error(current($this->tag->firstErrors));
    }
}
