<?php
/**
 * Created by huxin.
 * User: huxin
 * Date: 2019-02-27
 * Time: 09:41
 */

namespace backend\controllers;


use app\models\Chat;

class ChatController extends BasicController
{
    public $enableCsrfValidation = false;
    private $chat;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->chat = new Chat();
    }

    /**
     * 获取说说列表
     * Date: 2019-02-27 10:09
     * @return \yii\web\Response
     */
    public function actionChatList()
    {
        $data = $this->get();
        $this->chat->scenario = 'chatList';
        $this->chat->attributes = $data;
        if($this->chat->validate()){
            $list = $this->chat->find()
                ->offset(($data['pageNum'] - 1) * $data['pageSize'])
                ->limit($data['pageSize'])
                ->orderBy('created_at DESC')
                ->all();
            return !empty($list)?$this->success('获取说说列表成功！',$list)
                :$this->error('暂无说说列表数据！');
        }
        return $this->error(current($this->chat->firstErrors));
    }

    /**
     * 添加说说
     * Date: 2019-02-27 10:09
     * @return \yii\web\Response
     */
    public function actionChatAdd()
    {
        $data = $this->post();
        $this->chat->scenario = 'addChat';
        $this->chat->attributes = $data;
        if($this->chat->validate()){
            $res = $this->chat->save(false);
            return $res?$this->success('添加标签成功！')
                :$this->error('添加标签失败，请稍后再试！');
        }
        return $this->error(current($this->chat->firstErrors));
    }

    /**
     * 更新说说
     * Date: 2019-02-27 10:09
     * @return \yii\web\Response
     */
    public function actionChatUpdate()
    {
        $data = $this->post();
        $this->chat->scenario = 'updateChat';
        $this->chat->attributes = $data;
        if($this->chat->validate()){
            $exist_chat = $this->chat->findOne($data['id']);
            $exist_chat->content = $data['content'];
            $exist_chat->is_show = $data['is_show'];
            $res = $exist_chat->save(false,['content','is_show','updated_at']);
            return $res?$this->success('修改标签成功！')
                :$this->error('修改标签失败，请稍后再试！');
        }
        return $this->error(current($this->chat->firstErrors));
    }

    /**
     * 删除说说
     * Date: 2019-02-27 10:10
     * @return \yii\web\Response
     */
    public function actionDelChat()
    {
        $data = $this->post();
        $this->chat->scenario = 'chatDelete';
        $this->chat->attributes = $data;
        if($this->chat->validate()){
            $exist_chat = $this->chat->findOne($data['id']);
            $res = $exist_chat->delete();
            return $res?$this->success('删除标签成功！')
                :$this->error('删除标签失败，请稍后再试！');
        }
        return $this->error(current($this->chat->firstErrors));
    }
}
