<?php
/**
 * Created by huxin.
 * User: huxin
 * Date: 2019-03-15
 * Time: 09:47
 */

namespace frontend\controllers;


use frontend\models\Category;
use yii\web\Controller;

class BasicController extends Controller
{
    public function beforeAction($action)
    {
        $this->getCategoryData();
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }


    private function getCategoryData()
    {
        $list = Category::find()
            ->with('children')
            ->where(['pid'=>0])
            ->asArray()
            ->all();
        \Yii::$app->view->params['dh'] = $list;
    }
}
